version: '3.8'

services:
  # FastAPI 백엔드 서비스
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: memento-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - memento-network
    depends_on:
      - redis  # WebSocket 메시지 브로커로 사용 (선택사항)

  # React 프론트엔드 서비스 (개발 환경)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: memento-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost/api
      - VITE_WS_URL=ws://localhost/api/v1/ws
    networks:
      - memento-network
    depends_on:
      - backend

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: memento-nginx
    ports:
      - "80:80"
      - "443:443"  # HTTPS용 (SSL 인증서 설정 시)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # SSL 인증서 볼륨 (필요시)
      # - ./ssl:/etc/nginx/ssl:ro
    networks:
      - memento-network
    depends_on:
      - backend
      - frontend

  # Redis (WebSocket 메시지 브로커 및 세션 저장소 - 선택사항)
  redis:
    image: redis:7-alpine
    container_name: memento-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - memento-network

  # PostgreSQL 데이터베이스 (로컬 개발용 - Supabase 대신 사용 시)
  # database:
  #   image: postgres:15
  #   container_name: memento-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: memento_box
  #     POSTGRES_USER: memento_user
  #     POSTGRES_PASSWORD: memento_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
  #     - ./database/seed_data.sql:/docker-entrypoint-initdb.d/02-seed.sql
  #   networks:
  #     - memento-network

networks:
  memento-network:
    driver: bridge

volumes:
  redis_data:
  # postgres_data:  # PostgreSQL 사용 시 주석 해제